### ISSUE TITLE
Doesn't work in 0.107

### ISSUE THREAD

**Issue by i00** [gadgetchnnel/lovelace-card-templater#14] opened 2020-03-22 07:04 UTC
```yaml
type: 'custom:card-templater'
card:
  type: entities
  title: My Title
  entities:
    - type: 'custom:hui-text-entity-row'
      entity: sun.sun
      name_template: Home
      icon_template: 'mdi:home'
```
.. Shows no icon and '-' as the name

**Comment by sebk-666** [comment] 2020-03-23 13:48
Same here.
I installed this for the first time to give it a try (using HACS).
I want to create a picture card showing the image from the `cover_image` attribute of the `discogs_random_record` sensor.

Putting this:
```
{{ state_attr("sensor.discogs_random_record", "cover_image") }}
```
in the Lovelace developer-tools/template frontend, gets me this output:
```
https://img.discogs.com/W204y41r4tjU1FLNJS8oTeFF_Z0=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9596944-1565710103-8460.jpeg.jpg
```
which is a valid image URL.

But adding a card-templater card only shows the broken image symbol:
```yaml
card:
  image_template: '{{ state_attr("sensor.discogs_random_record", "cover_image") }}'
  type: picture
type: 'custom:card-templater'
```
Trying to debug the template value by templating the "contents" field of a markdown card instead, only shows "-".

**Comment by i00** [comment] 2020-03-24 03:04
Ok for some reason entities is now required???
Add:
entities:
  - sun.sun
..to fix..
This used to auto monitor entities for changes... so not sure why it is required ??? (i like the option for dynamic stuff that cannot be picked up automatically though)

**Comment by sebk-666** [comment] 2020-03-24 07:50
Adding "`entities: sensor.discogs_random_record`" doesn't change anything for me.

**Comment by gadgetchnnel** [comment] 2020-03-24 08:02
@sebk-666 entities needs to be an array, so your config would look something like:

```
type: 'custom:card-templater'
card:
  image_template: '{{ state_attr("sensor.discogs_random_record", "cover_image") }}'
  type: picture
entities:
  - sensor.discogs_random_record
```

With the way I am applying templates now it may be possible to extract the entities from the template and avoid the need for this but for now it is required.

**Comment by sebk-666** [comment] 2020-03-24 08:10
I tried that too, without luck.
Then I copied&pasted your version into a new card configuration and it worked.
Don't see the difference to what I had, though. Strange.

Anyway, thanks for your help! :)

**Comment by gadgetchnnel** [comment] 2020-03-24 08:33
@sebk-666 Possibly some sort of odd formatting error - I've had issues before with hyphens that were actually em dashes, quotes which were smart quotes, non-printing characters etc. (which are hard to spot).

Closing this for now as it is working as intended.

**Closed by gadgetchnnel** 2020-03-24 08:33 UTC

**Comment by i00** [comment] 2020-03-25 00:41
@gadgetchnnel .. please keep this .. I have some stuff that needs to be updated that can't "extract the entities from the template" automatically ... would be good if it could automatically do this but also watch any specified entities ... just make it optional :).
